### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by pamtbaau** [ly95/vsc.phpmd#12]
When I run the following command from the command prompt on Windows 10 all works fine:
`$ C:/DevTools/xampp/php/phpmd [path]/file.php xml unusedcode` or simply `$ phpmd file.php xml unusedcode`

I have the following settings in vs.code.
settings.json:

```
"phpmd.enabled": true,
"phpmd.validate.executablePath": "C:/DevTools/xampp/php/phpmd",
"phpmd.validate.rulesets": "cleancode,codesize,controversial,design,naming,unusedcode"
```

Using VS.code version 1.2.1

Any ideas for what I might be doing wrong?

**Comment by pamtbaau** [comment]
I noticed your first call to phpmd is `--version`. 

The following call is being issued by the phpmd.bat file:
`\DevTools\xampp\php\.\php.exe "\DevTools\xampp\php\phpmd.phar" --version`

The result of this call is: PHPMD 2.4.3

**Comment by pamtbaau** [comment]
After exiting/restarting vscode a couple of times, playing with the settings, switching projects. Testing with Netbeans, etc etc. It finally works...

The following is the effect of settings:
With `"phpmd.validate.executablePath": "C:/DevTools/xampp/php/phpmd"`
You call `phpmd.bat` with the argument `--version`

With `"phpmd.validate.executablePath": "C:/DevTools/xampp/php/phpmd.bat"`
You call `phpmd.bat` with `--version` and after that with the full set of filename, format and rules

NB. I have tried `phpmd.bat` before because that works well in Netbeans but didn't have much success in vscode. But after exiting/restarting, switching projects etc. `phpmd.bat` seems to be the right setting in my case.

Btw. what triggers the execution of phpmd?

**Comment by julihermes** [comment]
Not work for me.

I found this exception in developer tool:

```
shell.ts:400
channel closed: Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:523:16)
    at IPCMessageWriter.write (C:\Users\julih\.vscode\extensions\linyang95.phpmd-1.1.1\node_modules\vscode-jsonrpc\lib\messageWriter.js:34:22)
    at Object.connection.sendNotification (C:\Users\julih\.vscode\extensions\linyang95.phpmd-1.1.1\node_modules\vscode-jsonrpc\lib\main.js:180:27)
    at Object.result.didChangeConfiguration (C:\Users\julih\.vscode\extensions\linyang95.phpmd-1.1.1\node_modules\vscode-languageclient\lib\main.js:52:71)
    at LanguageClient.onDidChangeConfiguration (C:\Users\julih\.vscode\extensions\linyang95.phpmd-1.1.1\node_modules\vscode-languageclient\lib\main.js:489:28)
    at LanguageClient.<anonymous> (C:\Users\julih\.vscode\extensions\linyang95.phpmd-1.1.1\node_modules\vscode-languageclient\lib\main.js:475:81)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:8778)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:10231)
    at e.$acceptConfigurationChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:2136)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:28971)
```

Any solution?
