### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by ToujouAya** [ly95/vsc.phpmd#21]
I got this bug when phpmd install.  How can I fix this 

```
Error: spawn e:\Work\Projects\chuohDev\Source\vendor\bin\phpmd ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Error - 5:44:10 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by ly95** [comment]
I think I already know where the issue is. The next version will be resolved.

**Comment by ToujouAya** [comment]
@ly95 
Nice
